// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using icestats_api.Data;

#nullable disable

namespace icestats_api.Migrations
{
    [DbContext(typeof(IceStatsDbContext))]
    [Migration("20260412234855_AddSkaterFullNameToGoalLeaders")]
    partial class AddSkaterFullNameToGoalLeaders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("icestats_api.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("icestats_api.Models.NHL.NhlGoalLeader", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "playerId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("Assists")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "assists");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "firstName");

                    b.Property<int>("GameWinningGoals")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "gameWinningGoals");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "gamesPlayed");

                    b.Property<int>("Goals")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "goals");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "lastName");

                    b.Property<int>("OverTimeGoals")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "overTimeGoals");

                    b.Property<int>("PenaltyMinutes")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "pim");

                    b.Property<int>("PlusMinus")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "plusMinus");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "points");

                    b.Property<string>("Position")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "position");

                    b.Property<int>("PowerPlayGoals")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "powerPlayGoals");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("ShotPercentage")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "shotPctg");

                    b.Property<int>("Shots")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "shots");

                    b.Property<string>("SkaterFullName")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "skaterFullName");

                    b.Property<string>("TeamAbbreviation")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "teamAbbrevs");

                    b.HasKey("PlayerId");

                    b.ToTable("NhlGoalLeaders");
                });

            modelBuilder.Entity("icestats_api.Models.NHL.NhlSkater", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "playerId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("Assists")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "assists");

                    b.Property<int>("GameWinningGoals")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "gameWinningGoals");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "gamesPlayed");

                    b.Property<int>("Goals")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "goals");

                    b.Property<int>("OverTimeGoals")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "otGoals");

                    b.Property<int>("PenaltyMinutes")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "penaltyMinutes");

                    b.Property<int>("PlusMinus")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "plusMinus");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "points");

                    b.Property<string>("Position")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "positionCode");

                    b.Property<int>("PowerPlayGoals")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "ppGoals");

                    b.Property<int>("PowerPlayPoints")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "ppPoints");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "seasonId");

                    b.Property<int>("ShortHandedGoals")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "shGoals");

                    b.Property<int>("ShortHandedPoints")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "shPoints");

                    b.Property<double?>("ShotPercentage")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "shootingPct");

                    b.Property<int>("Shots")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "shots");

                    b.Property<string>("SkaterFullName")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "skaterFullName");

                    b.Property<string>("TeamAbbreviations")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "teamAbbrevs");

                    b.Property<double?>("TimeOnIcePerGame")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "timeOnIcePerGame");

                    b.HasKey("PlayerId");

                    b.ToTable("NhlSkaters");
                });

            modelBuilder.Entity("icestats_api.Models.NHL.NhlStanding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "abbreviation");

                    b.Property<string>("DivisionRank")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "divisionRank");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "gamePlayed");

                    b.Property<string>("LeagueAbbrev")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "leagueAbbrev");

                    b.Property<string>("LeagueRank")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "leagueRank");

                    b.Property<int>("Losses")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "losses");

                    b.Property<int>("OvertimeLosses")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "otLosses");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "points");

                    b.Property<double?>("PointsPercentage")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "ptsPctg");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TeamName")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "teamName");

                    b.Property<int>("Wins")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "wins");

                    b.HasKey("Id");

                    b.ToTable("NhlStandings");
                });

            modelBuilder.Entity("icestats_api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Team")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("icestats_api.Models.PlayerStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<int>("PenaltyMinutes")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PlusMinus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("icestats_api.Models.PlayerStat", b =>
                {
                    b.HasOne("icestats_api.Models.Game", "Game")
                        .WithMany("PlayerStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("icestats_api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("icestats_api.Models.Game", b =>
                {
                    b.Navigation("PlayerStats");
                });
#pragma warning restore 612, 618
        }
    }
}
